version: "3"

services:
  java:
    image: gradle:jdk17
    volumes:
      - ./backend/select_lunch:/app
    networks:
      - our_net
    container_name: java_select_lunch
    command: sleep infinity

  react:
    image: node:21
    volumes:
      - ./frontend:/app
    networks:
      - our_net
    ports:
      - "3000:3000"
    container_name: react_select_lunch
    command: sleep infinity

networks:
  our_net:
    driver: bridge